name: ENSIAS Departments CD

# Trigger on push to main (after PR merge)
on:
  push:
    branches: [main]

jobs:
  # Job 1: Build and Push Backend Services (with proper dependency order)
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build in correct order to handle dependencies
      - name: Build and push common-models
        run: |
          cd Back-End
          # Install parent POM first
          mvn clean install -N
          cd common-models
          docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/ensias-deps/common-models:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ensias-deps/common-models:latest

      - name: Build and install common-models locally
        run: |
          cd Back-End/common-models
          mvn clean install -DskipTests

      - name: Build and push other services
        run: |
          cd Back-End
          for service in admin auth chef-dep prof-dep; do
            echo "Building $service..."
            cd $service
            docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/ensias-deps/$service:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/ensias-deps/$service:latest
            cd ..
          done

  # Job 2: Build and Push Frontend
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          cd Front-End
          docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/ensias-deps/frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ensias-deps/frontend:latest

  # Job 3: Deploy to VM
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ~/ensias-departments-platform
            
            # Pull latest code
            git pull origin main
            
            # Create .env file from secrets
            cat > .env << EOF
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=5432
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRATION=86400000
            SPRING_DEVTOOLS_RESTART_ENABLED=false
            SPRING_DEVTOOLS_LIVERELOAD_ENABLED=false
            UPLOAD_DIR=./uploads
            EOF
            
            # Pull latest Docker images
            docker-compose -f docker-compose.prod.yml pull
            
            # Restart services with latest code and images
            docker-compose -f docker-compose.prod.yml up -d
            
            # Clean up old images
            docker image prune -f