name: ENSIAS Departments CI

# Trigger only on PR to main branch
on:
  pull_request:
    branches: [main]

jobs:
  # Job 1: Build parent and common-models first
  build-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install parent POM
        run: |
          cd Back-End
          mvn clean install -N

      - name: Build and install common-models
        run: |
          cd Back-End/common-models
          mvn clean install -DskipTests

      - name: Cache built artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/com/departement
          key: ${{ runner.os }}-built-artifacts-${{ github.sha }}

  # Job 2: Test Backend Services in Parallel
  backend-tests:
    runs-on: ubuntu-latest
    needs: build-common
    strategy:
      matrix:
        service: [admin, auth, chef-dep, prof-dep]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Restore Maven dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Restore built artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/com/departement
          key: ${{ runner.os }}-built-artifacts-${{ github.sha }}

      - name: Test ${{ matrix.service }}
        run: |
          cd Back-End/${{ matrix.service }}
          mvn clean test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.service }}
          path: Back-End/${{ matrix.service }}/target/surefire-reports/

  # Job 3: Test common-models separately
  test-common-models:
    runs-on: ubuntu-latest
    needs: build-common
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Restore Maven dependencies cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test common-models
        run: |
          cd Back-End/common-models
          mvn clean test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-common-models
          path: Back-End/common-models/target/surefire-reports/

  # Job 4: Test Frontend
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          cd Front-End
          npm ci

      - name: Build frontend
        run: |
          cd Front-End
          npm run build

  # Job 5: Summary
  ci-summary:
    runs-on: ubuntu-latest
    needs: [backend-tests, test-common-models, frontend-tests]
    if: always()
    steps:
      - name: CI Results
        run: |
          echo "✅ Common models tests: ${{ needs.test-common-models.result }}"
          echo "✅ Backend tests: ${{ needs.backend-tests.result }}"
          echo "✅ Frontend tests: ${{ needs.frontend-tests.result }}"